'use strict';

// Generates sample_output.json — the required deliverable showing our service's
// output for the public sample cases. Run: node scripts/gen_sample_output.js

const fs = require('fs');
const path = require('path');
const { analyzeTicket } = require('../src/analyze');
const pack = require('../SUST_Preli_Sample_Cases.json');

(async () => {
  const results = [];
  for (const c of pack.cases) {
    const output = await analyzeTicket(c.input);
    results.push({ id: c.id, label: c.label, input: c.input, output });
  }
  const out = {
    _meta: {
      title: 'QueueStorm Investigator — Sample Outputs',
      note: 'Generated by our service (rule-based mode) from the public sample inputs.',
      endpoint: 'POST /analyze-ticket',
      case_count: results.length,
    },
    cases: results,
  };
  const dest = path.join(__dirname, '..', 'sample_output.json');
  fs.writeFileSync(dest, JSON.stringify(out, null, 2) + '\n');
  console.log(`Wrote ${results.length} cases to ${dest}`);
})();
